image: docker
services:
  - docker:dind
stages:
  - deploy
step-deploy-dev:
  stage: deploy
  script:
    - docker build -t app/vuecyclopedia .
    - docker run -d -p 80:80 --rm --name todoapp app/vuecyclopedia